#!/usr/bin/env bun

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { classifyRepoPath, type RepoPathClassification } from '../../lib/nexus/repo-taxonomy';

const ROOT = join(import.meta.dir, '..', '..');
const OUTPUT_PATH = 'docs/architecture/repo-path-inventory.md';
const SELF_PATH = 'scripts/repo/path-inventory.ts';

function gitLsFiles(): string[] {
  const result = Bun.spawnSync(['git', 'ls-files'], { cwd: ROOT });
  if (result.exitCode !== 0) {
    const stderr = new TextDecoder().decode(result.stderr).trim();
    throw new Error(`git ls-files failed: ${stderr}`);
  }
  return new TextDecoder().decode(result.stdout).trim().split('\n').filter(Boolean);
}

function allInventoryPaths(): string[] {
  const tracked = gitLsFiles();
  const generatedAndNew = [SELF_PATH, OUTPUT_PATH];
  return Array.from(new Set([...tracked, ...generatedAndNew])).sort();
}

function md(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function countBy<T extends string>(items: RepoPathClassification[], key: (item: RepoPathClassification) => T): Record<T, number> {
  return items.reduce(
    (acc, item) => {
      const value = key(item);
      acc[value] = (acc[value] ?? 0) + 1;
      return acc;
    },
    {} as Record<T, number>
  );
}

function renderCountTable(title: string, counts: Record<string, number>): string {
  const rows = Object.entries(counts)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, count]) => `| ${name} | ${count} |`)
    .join('\n');
  return `## ${title}\n\n| Name | Files |\n|---|---:|\n${rows}\n`;
}

function renderInventory(paths: string[]): string {
  const classifications = paths.map((path) => classifyRepoPath(path));
  const categoryCounts = countBy(classifications, (item) => item.category);
  const policyCounts = countBy(classifications, (item) => item.move_policy);

  const rows = classifications
    .map((item) =>
      [
        `\`${md(item.current_path)}\``,
        `\`${md(item.target_path)}\``,
        md(item.category),
        md(item.move_policy),
        md(item.risk_level),
        md(item.rule),
        md(item.rationale),
      ].join(' | ')
    )
    .map((row) => `| ${row} |`)
    .join('\n');

  return `# Nexus Repo Path Inventory

Generated by \`${SELF_PATH}\`.

- File source: \`git ls-files\` plus this generator and this inventory path when present
- Total paths: ${classifications.length}
- Purpose: make the repo taxonomy explicit enough that future physical moves can be reviewed and tested before they affect installed Nexus runtimes.

${renderCountTable('Category Counts', categoryCounts)}

${renderCountTable('Move Policy Counts', policyCounts)}

## Inventory

| Current path | Target path | Category | Move policy | Risk | Rule | Rationale |
|---|---|---|---|---|---|---|
${rows}
`;
}

const content = renderInventory(allInventoryPaths());
const outputAbs = join(ROOT, OUTPUT_PATH);

if (process.argv.includes('--check')) {
  const existing = existsSync(outputAbs) ? readFileSync(outputAbs, 'utf8') : '';
  if (existing !== content) {
    console.error(`${OUTPUT_PATH} is stale. Run: bun run scripts/repo/path-inventory.ts`);
    process.exit(1);
  }
  console.log(`${OUTPUT_PATH} is up to date`);
} else {
  writeFileSync(outputAbs, content);
  console.log(`Wrote ${OUTPUT_PATH}`);
}
